<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information. -->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <IsPackable>true</IsPackable>
    <DebugType>embedded</DebugType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <CreateDocumentationFile>true</CreateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <SignOutput>false</SignOutput>
    <IncludeSomeVerInfo>true</IncludeSomeVerInfo>
    <IsWixTestSupportProject>true</IsWixTestSupportProject>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\..\.agent\skills\burn-ba-unit-test-authoring\SKILL.md" Pack="true" PackagePath="tools/skills/burn-ba-unit-test-authoring/SKILL.md" />
    <None Include="build\WixToolset.Burn.UnitTest.targets" Pack="true"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" />
    <PackageReference Include="PanelSwWix4.BootstrapperApplicationApi" />
  </ItemGroup>

</Project>
