<Project>
  <PropertyGroup>
    <OutputType>Bundle</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PanelSwWix4.BootstrapperApplications.wixext" />
    <PackageReference Include="PanelSwWix4.Util.wixext" />
    <PackageReference Include="PanelSwWix4.NetFx.wixext" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\TestBA\TestBAWixlib\testbawixlib.wixproj" />
    <ProjectReference Include="..\PuomPkg1\PuomPkg1.wixproj" />
    <ProjectReference Include="..\PuomPkg2\PuomPkg2.wixproj" />
  </ItemGroup>
</Project>